### ISSUE TITLE
fail: pip install git+https://github.com/iree-org/iree-torch.git, How can I install iree-torch with existing torch_mlir?

### ISSUE THREAD

**Issue by zhping5678** [iree-org/iree-torch#74]
When I tried to install iree-torch by 'pip install git+https://github.com/iree-org/iree-torch.git', it reports below. 

Collecting git+https://github.com/iree-org/iree-torch.git
  Cloning https://github.com/iree-org/iree-torch.git to /tmp/pip-req-build-20px4dwa
  Running command git clone --filter=blob:none --quiet https://github.com/iree-org/iree-torch.git /tmp/pip-req-build-20px4dwa
  Resolved https://github.com/iree-org/iree-torch.git to commit 5fbaf505384eef01f63a618bcc4e59929b87f676
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: iree-compiler in /anaconda3/envs/python38/lib/python3.8/site-packages (from iree-torch==0.0.1) (20220930.282)
Requirement already satisfied: iree-runtime in /anaconda3/envs/python38/lib/python3.8/site-packages (from iree-torch==0.0.1) (20220930.282)
**ERROR: Could not find a version that satisfies the requirement torch-mlir (from iree-torch) (from versions: none)
ERROR: No matching distribution found for torch-mlir**

I know from another issue that I can install torch_mlir individually, however, I have built torch_mlir from source code and set pythonpath. I can import torch_mlir in other python source code successfully, like below.

Python 3.8.15 (default, Nov 24 2022, 15:19:38)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
> import torch
> import torch_mlir
> import torch_mlir_e2e_test

How can I install iree-torch with existing torch_mlir?

**Comment by dellis23** [comment]
Since you're building and installing it yourself, I'm not sure what may have gone wrong.  It seems like pip doesn't think you have it installed, for whatever reason.  Some workarounds I can think of would be to git clone the repo, remove the `torch_mlir` requirement, and install from there (since you're confident it will be available at import time).

It [looks like](https://stackoverflow.com/questions/12759761/pip-force-install-ignoring-dependencies) pip also has a `--no-dependencies` flag you could try using.

**Comment by zhping5678** [comment]
Thank you. I successfully installed iree_torch by ` pip install git+https://github.com/iree-org/iree-torch.git --no-dependencies`
